package demo;

import ooadrefactoring.Message;

public class TemplateMethodDemo {
    public static void main(String[] args) {

    }
}

class Logger {
    public void log(Message m, key) {
        //....
        //....
        strategy.step(); //strategy [GoF]
        //....
        //....
    }

    public void log(int m) {
        //.....
        //.....
        step1();
        //.....
        //.....
    }

    public void log(String m) {
        //.....
        //.....
        step2();
        //.....
        //.....
    }
}