package com.acme.dbo.txlog;

/**
 *
 */
public class Application {
    public static void main(String[] args) {
        //........
        //........
        while (notAlwaysTrue()) {

        }
        //........
        //........
        //........
//        new Facade();
        Facade.log(1);
        //...
        //...
        //...
        //ClassLoader.unload(Facade.class)
        //......
        //......
        //......
    }

    private static boolean notAlwaysTrue() {
        return false;
    }
}
