package com.acme.dbo.txlog;

public class Application {
    public static void main(String[] args) {
        //........
        //........
        //........
        //........
        //........
        Facade.log(1);
        //...
        //...
        //...
        //ClassLoader.unload(Facade.class)
        //......
        //......
        //......
    }
}
