package com.acme.dbo.txlog;

public class Application {
    public static void main(String[] args) {
        //.....
        //Cl.load()
        //.....
        //.....
        //.....
        Facade.log(1);
        //...
        //...
        //...
        //...
        Facade.log(1);
        //ClassLoader.
    }
}
